### ISSUE TITLE
Replace docfx xref with direct links in markdown

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#26]
Right now we have a lot of broken links which just make browsing navigation harder. Even if we bring it back, UID does not work locally and does not work for anyone who just browses the repo. Since docfx also supports relative file links a suggestion is dumping UID and using plain markdown.

**Removing the uids has the following disadvantages:**

- Sometimes there are links between pathes that are very long and hard to understand
- API references cannot be linked by path and must have a uid
- Refactorings in documentation are getting harder because you must know which file is linking to the moved file
- The plan was to generate a complete documentation for moryx and not for each project itself. So you must know pathes from other repos. This is impossible.
- Our documentation gets bigger an bigger and browing it by files is confusing anyway
- Local hosting is very easy by .\Build.ps1 -GenerateDocs
- Mapping of sourcecode to documentation does not work in plain markdown
- Docfx has a very well working search implementation
- We should definitly work on hosting the documentation and link from this repo. Have a look at projects like https://github.com/dotnet/docs - it is a very well structured documentation. It can be browsed in repository but links also not work.

**Comment by Toxantron** [comment]
So I had a look at https://github.com/dotnet/docs and they do use path links as well. Their documentation completely works on Github, you can event step through previous and next in the tutorials. Look at the [documentation for delegates](https://github.com/dotnet/docs/blob/master/docs/csharp/delegate-class.md) for example.

Inline examples are broken, but still link to the correct file, see [here](https://github.com/dotnet/docs/blob/master/docs/csharp/delegates-patterns.md#building-a-second-output-engine) and [some xref are unresolved](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md), but all markdown links use the path instead of UUID.

We should have hosted documentation, but that looks like working documentation is common on GitHub. We can also link to files using their path. I doubt the path changes more often than the namespace. Thoughts?

**Comment by dbeuchler** [comment]
We need `xref` if we generate a single MORYX documentation, reference APIs or reference Code. For the links within the documentation, we need no `xref` for now and this can be changed.

**Comment by 1nf0rmagician** [comment]
Done by @jsonBackup in #220
