### ISSUE TITLE
ResourceInitializerExtensions provide extensions for object

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Framework#475]
**Describe the bug**

The public `ResourceInitializerExtensions` adds extensions to object instead of limit to `Resource`. A `where` clause should be added: `where TResource : Resource`

````
public static class ResourceInitializerExtensions
{
    /// <summary>
    /// Allows to configure a <see cref="Resource"/> with method chaining
    /// </summary>
    /// [...]
    public static TResult Configure<TResult>(this TResult configurable, Action<TResult> onConfigure)
    {
        onConfigure(configurable);
        return configurable;
    }
[...]
}
````

**Comment by 1nf0rmagician** [comment]
First of all, thanks a lot for the contribution 😊

After discussing this issue, @Toxantron and I agree that this is intended an not actually a bug. The idea behind this method is to also allow for the configuration of e.g. an `IVisualInstructor` with method chaining. Since this is but one example of interfaces used in the context of resources which do not directly relate to the `Resource` base class, we want to keep this extension without the proposed constraint.

**Comment by dbeuchler** [comment]
I also thought about that but shouldn't be minimum base interface `IResource`/ `IPublicResource` also for `IVisualInstructor` (by the way, it is)?

**Comment by 1nf0rmagician** [comment]
Yeah, for `IVisualInstructor` that is true, but we also have the featureset related to the `ResourceAvailableAsAttribute` and at least to my understanding the whole point of this attribute is to be able to use interfaces for resources even outside the module that do not need to derive from `IResource`, the `IProcessDataPublisher` would be an example for that 🤔

**Comment by 1nf0rmagician** [comment]
You need the exact type, but are not forced to not use these interfaces afterwards. Neither did we ever give out a best practice not to use such interfaces in an initializer. Just to be clear, I don't know of an example where it would be used on such an interface, but we neither prevented nor discouraged this in the past and that would, in our opinion, make this compiler breaking change/fix a harsh approach, don't you think?
